##################
# Website config #
##################

name: Angry Gecko

navigation:
  - title: Home
    url: /
  - title: The Team
    url: /who-we-are/
  - title: Get Involved
    url: /how-you-can-help/
  - title: Development
    url: /developing-the-car/
  - title: Sponsors
    url: /sponsors/
  - title: Contact
    url: /contact/

footer_copyright: |
 <div class="footer-element">&copy; Shaun S. 2013-2014 All rights reserved.</div>
 <div class="footer-element"><a href="http://validator.w3.org/check?uri=http%3A%2F%2Fangrygecko.org%2F"><i class="fa fa-html5"></i> <span>HTML 5 Valid</span></a></div>
 <div class="footer-element">Website design: <a href="https://github.com/technicalguy"><i class="fa fa-github-square"></i> <span>Shaun S</span></a></div>
 <!--<div class="footer-element">Photography: <a href="https://www.flickr.com/photos/insertphotoshere/"><i class="fa fa-flickr"></i> <span>Shaun S</span></a></div>-->
 <div class="footer-element">Template design: <a href="http://html5up.net/"><span>HTML5 UP</span></a></div>

footer_main: |
 <div class="3u">
   <!-- Links -->
     <section class="widget-links">
       <h2>Greenpower</h2>
       <ul class="style2">
         <li><a href="http://www.greenpower.co.uk/">Greenpower Education Trust</a></li>
         <li><a href="http://www.greenpower.co.uk/racing/formula24">IET Formula 24</a></li>
         <li><a href="http://www.greenpower.co.uk/events/">Greenpower Events</a></li>
       </ul>
     </section>
 
 </div>
 <div class="3u">
 
   <!-- Links -->
     <section class="widget-links">
       <h2><a href="/sponsors/">Sponsors</a></h2>
       <ul class="style2">
         <li><a href="http://chelsea-academy.org/">Chelsea Academy</a></li>
         <li><a href="http://chelsea-academy-foundation.org/">Chelsea Academy Foundation</a></li>
       </ul>
     </section>
 
 </div>
 <div class="3u">
 
   <!-- Links -->
     <section class="widget-links">
       <h2><a href="/sponsors/">Sponsors</a></h2>
       <ul class="style2">
         <li><a href="http://www.alliants.com/">Alliants</a></li>
         <li><a href="http://www.korteq.com/">KorteQ</a></li>
       </ul>
     </section>
 
 </div>
 <div class="3u">
 
  <!-- Contact -->
    <section class="widget-contact last">
      <h2><a href="/contact/">Contact Us</a></h2>
      <ul class="fa-ul">
        <li><a href="https://www.facebook.com/angry.gecko.cart"><i class="fa-li fa fa-facebook-square"></i>Facebook</a></li>
        <li><a href="https://plus.google.com/109525757211133772308"><i class="fa-li fa fa-google-plus-square"></i>Google+</a></li>
        <li><a href="mailto:angrygecko@chelsea-academy.org"><i class="fa-li fa fa-envelope"></i>angrygecko@chelsea-academy.org</a></li>
      </ul>
    </section>
 
 </div>

#######################
# Jekyll config stuff #
#######################

markdown: redcarpet
pygments: true
safe: true
timezone: Europe/London
encoding: utf-8
keep_files: ['.git']
redcarpet:
    extensions: ['smart']
# source: .
# desnination: _site